package org.opencsd.imdbplus.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 Sample user item JSON:
 {
 "username": "tester",
 "email": "tester@columbia.edu",
 "accountSetting": {
 "isPrivate": false,
 "isAdult": true
 }
 }
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "user")
public class User {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String userId;
  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String accessToken;
  @DynamoDBAttribute
  private String username;
  @DynamoDBAttribute
  private String email;
  @DynamoDBAttribute
  private AccountSetting accountSetting;

  public User(String username, String email, AccountSetting accountSetting) {
    this.username = username;
    this.email = email;
    this.accountSetting = accountSetting;
  }

  public String getUsername() {
    return username;
  }
}
